class_name MaterialLibrary
extends RefCounted

## Procedural surface textures, one set per named material family.
##
## Everything on the board except the ground used to be a flat colour. That is
## fine at a distance and falls apart the moment anything is near the camera: a
## wall, a turret and a rock lit the same way are three shades of the same
## material, and the eye reads the whole board as plastic. This generates, for
## each family, the three maps that make a surface a surface - an albedo
## variation, a tangent-space normal map, and a roughness map - from one shared
## noise field per family.
##
## Generated, never shipped. Same reason as the sound effects: no binary assets
## in the repo, and a surface becomes something that can be reasoned about in a
## JSON block instead of opened in an image editor. The families and their
## character live in data/materials.json, so art direction is tunable without
## touching code.
##
## Three properties this has to hold, all of them learned the hard way elsewhere
## in this renderer:
##
##   1. Generated ONCE. The library outlives the board - a level load reuses it
##      rather than rebuilding it - because generating ten families per level
##      load is a visible hitch, and on the web build it is a hitch on a machine
##      that was already the thing being complained about.
##   2. One field per family, not one per map. The old ground code called
##      _noise_field twice, once for the albedo and once for the normal, and
##      generated byte-identical data both times. The maps are different VIEWS of
##      one field, so the field is computed once and all three read it.
##   3. Nothing here can fail the game. A family missing from the data falls back
##      to a plain untextured material, because a surface that renders flat is a
##      cosmetic problem and a renderer that refuses to build is not.

## Quality tiers, mirroring the renderer's three.
##
## Measured in a browser on one board, and the reason this is a ladder rather
## than a switch: turning all three maps on cost 48% of the frame at the top
## tier and 9% at the middle one. The normal map is most of that - it is the map
## that has to be decoded and re-based per pixel, where the other two are plain
## fetches - so the middle tier drops it and keeps the albedo and roughness
## variation, which is most of what stops a surface reading as plastic.
##
##   DETAIL_FULL     albedo + normal + roughness
##   DETAIL_SIMPLE   albedo + roughness
##   DETAIL_PLAIN    nothing generated at all
enum { DETAIL_FULL, DETAIL_SIMPLE, DETAIL_PLAIN }

var _world: Dictionary = {}
var _families: Dictionary = {}
var _detail: int = DETAIL_FULL

## family name -> {"albedo": ImageTexture, "normal": ImageTexture,
##                 "roughness": ImageTexture}
var _cache: Dictionary = {}

func _init(world: Dictionary, families: Dictionary, detail: int = DETAIL_FULL) -> void:
	_world = world
	_families = families
	_detail = detail

## Rebuild at a different detail level.
##
## Returns true when the level actually changed, so the caller knows whether the
## board has to be rebuilt - the textures are baked into materials, and a
## material already handed to a MeshInstance does not re-read them.
func set_detail(detail: int) -> bool:
	if detail == _detail:
		return false
	_detail = detail
	# The cache is keyed by family, not by family-and-detail. Dropping it is
	# correct rather than wasteful: the tier is changed by a keypress a handful of
	# times per session, and keeping both tiers resident would hold texture memory
	# for a tier that is not being drawn.
	_cache.clear()
	return true

func detail() -> int:
	return _detail

## Whether this family has any generated maps at all.
func has_family(family: String) -> bool:
	return _detail != DETAIL_PLAIN and _families.has(family)

## Apply a family's maps to a material, and answer whether anything was applied.
##
## The tint stays the caller's business. These maps are all neutral - the albedo
## is grey centred on 1.0 so it multiplies whatever colour the family already had
## rather than replacing it - so a Ballistic turret stays its own colour and
## gains a surface, instead of every family converging on the texture's colour.
func apply(material: StandardMaterial3D, family: String) -> bool:
	if not has_family(family):
		return false
	var maps := _maps(family)
	if maps.is_empty():
		return false
	var spec: Dictionary = _families[family]
	material.albedo_texture = maps["albedo"]
	if _detail == DETAIL_FULL:
		material.normal_enabled = true
		material.normal_texture = maps["normal"]
		material.normal_scale = float(spec.get("normal_scale", 1.0))
	material.roughness_texture = maps["roughness"]
	material.roughness_texture_channel = BaseMaterial3D.TEXTURE_CHANNEL_RED
	# The texture carries the absolute roughness, so the scalar has to be 1.0 or
	# it would scale the whole map down - Godot multiplies the two. The family's
	# intended roughness is the CENTRE of the baked range instead, which is why
	# "roughness" is a property of the family in data rather than of the caller.
	material.roughness = 1.0
	material.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS
	material.texture_repeat = true
	var scale := float(spec.get("uv_scale", 1.0))
	material.uv1_scale = Vector3(scale, scale, scale)
	return true

## How many families have been generated so far. Test hook - it is the cheapest
## way to assert that the cache is a cache.
func generated_count() -> int:
	return _cache.size()

# --- generation ------------------------------------------------------------------------

func _maps(family: String) -> Dictionary:
	if _cache.has(family):
		return _cache[family]
	var spec: Dictionary = _families[family]
	var size := int(spec.get("size", 96))
	var field := _field(spec, size)
	# The normal map is not built at all below the top tier. It is the most
	# expensive of the three to generate as well as the most expensive to sample,
	# and a map nothing will read is pure load time. set_detail() drops the cache,
	# so moving back up to FULL rebuilds it.
	var maps := {
		"albedo": _albedo_map(field, size, float(spec.get("contrast", 0.35))),
		"normal": _normal_map(field, size, float(spec.get("relief", 2.5))) \
			if _detail == DETAIL_FULL else null,
		"roughness": _roughness_map(field, size,
			float(spec.get("roughness", 0.7)), float(spec.get("roughness_swing", 0.2))),
	}
	_cache[family] = maps
	return maps

## The family's height field: fractal value noise, plus optional panel grooves.
##
## Separate X and Y lattice counts are what let one generator produce materials
## that do not all look like the same grey static. Equal counts give isotropic
## grit (soil, stone); a wide X against a narrow Y gives directional streaking,
## which is asphalt dragged along the road, brushed metal on a turret housing,
## and the vertical grain of bark - three families that share every line of this
## code and do not look alike.
func _field(spec: Dictionary, size: int) -> PackedFloat32Array:
	var field := PackedFloat32Array()
	field.resize(size * size)
	field.fill(0.0)
	var lat_x: Array = spec.get("lattice_x", [4, 9, 19])
	var lat_y: Array = spec.get("lattice_y", lat_x)
	var weights: Array = spec.get("weights", [0.55, 0.3, 0.15])
	var seed_offset := int(spec.get("seed", 0))
	for o in mini(lat_x.size(), weights.size()):
		var nx := maxi(int(lat_x[o]), 1)
		var ny := maxi(int(lat_y[o]) if o < lat_y.size() else nx, 1)
		var weight := float(weights[o])
		for y in size:
			var fy := float(y) / float(size) * float(ny)
			var y0 := int(floor(fy))
			var ty := fy - float(y0)
			ty = ty * ty * (3.0 - 2.0 * ty)
			var ya := y0 % ny
			var yb := (y0 + 1) % ny
			var row := y * size
			for x in size:
				var fx := float(x) / float(size) * float(nx)
				var x0 := int(floor(fx))
				var tx := fx - float(x0)
				# Smoothstep, or the lattice shows as diamonds.
				tx = tx * tx * (3.0 - 2.0 * tx)
				var xa := x0 % nx
				var xb := (x0 + 1) % nx
				# Modulo on the lattice index, not on the pixel, is what makes the
				# result tile: the last column interpolates back to the first.
				var a00 := _hash_unit(xa + seed_offset, ya + o * 31)
				var a10 := _hash_unit(xb + seed_offset, ya + o * 31)
				var a01 := _hash_unit(xa + seed_offset, yb + o * 31)
				var a11 := _hash_unit(xb + seed_offset, yb + o * 31)
				var top: float = a00 + (a10 - a00) * tx
				var bottom: float = a01 + (a11 - a01) * tx
				field[row + x] += (top + (bottom - top) * ty) * weight

	var panel_x := int(spec.get("panel_x", 0))
	var panel_y := int(spec.get("panel_y", 0))
	var depth := float(spec.get("panel_depth", 0.0))
	if depth > 0.0 and (panel_x > 0 or panel_y > 0):
		_cut_panels(field, size, panel_x, panel_y, depth)
	return field

## Straight grooves at regular intervals, cut into the field.
##
## This is what separates a manufactured surface from a natural one. Noise alone
## reads as rock or soil however it is tuned, because nothing in nature repeats
## on a grid - so walls and turret housings get panel seams, and they stop
## looking like they were carved from the same stone as the scenery.
func _cut_panels(field: PackedFloat32Array, size: int, panel_x: int, panel_y: int,
		depth: float) -> void:
	var step_x := size / maxi(panel_x, 1)
	var step_y := size / maxi(panel_y, 1)
	for y in size:
		var on_y := panel_y > 0 and step_y > 0 and (y % step_y) == 0
		var row := y * size
		for x in size:
			var on_x := panel_x > 0 and step_x > 0 and (x % step_x) == 0
			if on_x or on_y:
				field[row + x] = maxf(field[row + x] - depth, 0.0)

## Grey variation centred on 1.0, so it multiplies the family's colour.
func _albedo_map(field: PackedFloat32Array, size: int, contrast: float) -> ImageTexture:
	var bytes := PackedByteArray()
	bytes.resize(size * size * 3)
	for i in size * size:
		var v := clampf(1.0 + (field[i] - 0.5) * contrast, 0.0, 1.0)
		var b := int(v * 255.0)
		var at := i * 3
		bytes[at] = b
		bytes[at + 1] = b
		bytes[at + 2] = b
	return _texture(bytes, size, Image.FORMAT_RGB8)

## A tangent-space normal map from the same field.
##
## This is what makes a flat polygon look like it has a surface. Central
## differences for the slope, encoded the way a normal map is: XY in red and
## green about a half-grey rest, Z in blue. The neighbour lookups wrap, because a
## map whose edges do not agree shows a seam every tile.
func _normal_map(field: PackedFloat32Array, size: int, strength: float) -> ImageTexture:
	var bytes := PackedByteArray()
	bytes.resize(size * size * 3)
	for y in size:
		var row := y * size
		var up := ((y - 1 + size) % size) * size
		var down := ((y + 1) % size) * size
		for x in size:
			var left := field[row + ((x - 1 + size) % size)]
			var right := field[row + ((x + 1) % size)]
			var nx := (left - right) * strength
			var ny := (field[up + x] - field[down + x]) * strength
			var inv := 1.0 / sqrt(nx * nx + ny * ny + 1.0)
			var at := (row + x) * 3
			bytes[at] = int((nx * inv * 0.5 + 0.5) * 255.0)
			bytes[at + 1] = int((ny * inv * 0.5 + 0.5) * 255.0)
			bytes[at + 2] = int((inv * 0.5 + 0.5) * 255.0)
	return _texture(bytes, size, Image.FORMAT_RGB8)

## Absolute roughness, swinging either side of the family's centre.
##
## Uniform roughness is the other half of why untextured surfaces read as
## plastic: a real surface is polished where it has been rubbed and dull where it
## has not, and that variation is most of what tells you a highlight is on metal
## rather than on paint. The pits in the field are the dull parts.
func _roughness_map(field: PackedFloat32Array, size: int, centre: float,
		swing: float) -> ImageTexture:
	var bytes := PackedByteArray()
	bytes.resize(size * size)
	for i in size * size:
		bytes[i] = int(clampf(centre + (field[i] - 0.5) * swing, 0.0, 1.0) * 255.0)
	return _texture(bytes, size, Image.FORMAT_L8)

## Mipmaps are not optional here.
##
## These textures are tiled small and viewed at a shallow angle across a board
## that is mostly horizon, which is the exact case that aliases: without mipmaps
## the far half of the ground crawls with sampling noise whenever the camera
## moves, and "the distance shimmers" is indistinguishable from "the frame rate
## is bad" to anyone who is not looking for it.
func _texture(bytes: PackedByteArray, size: int, format: int) -> ImageTexture:
	var image := Image.create_from_data(size, size, false, format, bytes)
	image.generate_mipmaps()
	return ImageTexture.create_from_image(image)

## Deterministic value hash in [0, 1).
##
## The same integer hash the renderer uses for its scatter, kept here so the
## library does not depend on the renderer. Determinism matters even though this
## is cosmetic: a texture that differed between two runs would make every
## screenshot comparison in the dev tools useless.
static func _hash_unit(x: int, y: int) -> float:
	var h := (x * 374761393 + y * 668265263) & 0x7fffffff
	h = (h ^ (h >> 13)) * 1274126177
	h = h & 0x7fffffff
	return float(h % 65536) / 65536.0
